added cloudhosted instructions
OpenLiberty/guide-microprofile-reactive-messaging-rest-integration pull request #55
Opened 2021-03-24 19:16 UTC by tt-le

2021-03-31 18:46 UTC, dmuelle requested changes
A question for clarification

2021-03-31 18:46 UTC, dmuelle commented on README.adoc
>  You can revisit the http://localhost:9085/inventory/systems[^] URL after a while, and you will notice the CPU `systemLoad`
You can revisit the http://localhost:9085/inventory/systems[^] URL after a while, and you will notice the CPU `systemLoad`
--->
You can revisit the http://localhost:9085/inventory/systems[^] URL after a while and the CPU `systemLoad` property for the systems  is changed.

this sentence is a little vague? is it possible to clarify how it has changed, or what about it is different? What is the user seeing that is different?

2021-04-01 13:08 UTC, gkwan-ibm commented on README.adoc
>  You can revisit the http://localhost:9085/inventory/systems[^] URL after a while, and you will notice the CPU `systemLoad`
hi @dmuelle
The value of the systemLoad property is changed. How's the following?
--->
You can revisit the http://localhost:9085/inventory/systems[^] URL after a while and the value of `systemLoad` property for the system is changed.

2021-04-01 13:25 UTC, dmuelle commented on README.adoc
>  You can revisit the http://localhost:9085/inventory/systems[^] URL after a while, and you will notice the CPU `systemLoad`
That's good, I would only add "the", and retain the plural of "systems", if the user is looking at values for multiple instances of the property:

You can revisit the http://localhost:9085/inventory/systems[^] URL after a while and the value of the `systemLoad` property for the systems is changed.

2021-04-01 13:28 UTC, dmuelle requested changes

2021-04-01 13:28 UTC, dmuelle commented on README.adoc
> +You can revisit the **inventory** service after a while by running the following curl command, and you will notice the CPU **systemLoad**
based on previous comment, recommend here:

You can revisit the **inventory** service after a while by running the following curl command:
```
curl http://localhost:9085/inventory/systems
```
Notice the CPU **systemLoad** property for the systems is changed.

2021-04-01 13:48 UTC, tt-le commented
@dmuelle thank you for the feedback! I made both changes. Was there anything else you wanted to add?

2021-04-01 14:07 UTC, dmuelle approved these changes
LGTM, thanks

2021-04-01 14:13 UTC, gkwan-ibm approved these changes

2021-04-01 14:44 UTC, merged